<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 tsets package | A Time Series Framework</title>
  <meta name="description" content="Documentation for the tsmodels framework" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 tsets package | A Time Series Framework" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Documentation for the tsmodels framework" />
  <meta name="github-repo" content="tsmodels/tsmodels.github.io" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 tsets package | A Time Series Framework" />
  
  <meta name="twitter:description" content="Documentation for the tsmodels framework" />
  

<meta name="author" content="The tsmodels team" />


<meta name="date" content="2020-11-25" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="tsmethods.html"/>
<link rel="next" href="tsissm.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-177357579-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  
  function gtag(){dataLayer.push(arguments);}
  
  gtag('js', new Date());
  
  gtag('config', 'UA-177357579-1');
</script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Time Series Forecasting Framework</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Installation</a></li>
<li class="chapter" data-level="2" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>2</b> Introduction</a></li>
<li class="chapter" data-level="3" data-path="tsmethods.html"><a href="tsmethods.html"><i class="fa fa-check"></i><b>3</b> tsmethods package</a><ul>
<li class="chapter" data-level="3.1" data-path="tsmethods.html"><a href="tsmethods.html#introduction"><i class="fa fa-check"></i><b>3.1</b> Introduction</a></li>
<li class="chapter" data-level="3.2" data-path="tsmethods.html"><a href="tsmethods.html#tsmethods:simulation"><i class="fa fa-check"></i><b>3.2</b> Ensembling Forecast Distributions</a></li>
<li class="chapter" data-level="3.3" data-path="tsmethods.html"><a href="tsmethods.html#demonstration"><i class="fa fa-check"></i><b>3.3</b> Demonstration</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tsets.html"><a href="tsets.html"><i class="fa fa-check"></i><b>4</b> tsets package</a><ul>
<li class="chapter" data-level="4.1" data-path="tsets.html"><a href="tsets.html#tsets:intro"><i class="fa fa-check"></i><b>4.1</b> Introduction</a></li>
<li class="chapter" data-level="4.2" data-path="tsets.html"><a href="tsets.html#tsets:taxonomy"><i class="fa fa-check"></i><b>4.2</b> Taxonomy of Models</a></li>
<li class="chapter" data-level="4.3" data-path="tsets.html"><a href="tsets.html#tsets:extensions"><i class="fa fa-check"></i><b>4.3</b> Extensions</a></li>
<li class="chapter" data-level="4.4" data-path="tsets.html"><a href="tsets.html#some-encompasing-alternatives"><i class="fa fa-check"></i><b>4.4</b> Some Encompasing Alternatives</a></li>
<li class="chapter" data-level="4.5" data-path="tsets.html"><a href="tsets.html#tsets:implementation"><i class="fa fa-check"></i><b>4.5</b> Package Implementation</a><ul>
<li class="chapter" data-level="4.5.1" data-path="tsets.html"><a href="tsets.html#tsets:implementation:constraints"><i class="fa fa-check"></i><b>4.5.1</b> Constraints</a></li>
<li class="chapter" data-level="4.5.2" data-path="tsets.html"><a href="tsets.html#tsets:implementation:initialization"><i class="fa fa-check"></i><b>4.5.2</b> Initialization</a></li>
<li class="chapter" data-level="4.5.3" data-path="tsets.html"><a href="tsets.html#tsets:implementation:transformations"><i class="fa fa-check"></i><b>4.5.3</b> Transformations</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="tsets.html"><a href="tsets.html#tsets:demonstration"><i class="fa fa-check"></i><b>4.6</b> Demonstration</a><ul>
<li class="chapter" data-level="4.6.1" data-path="tsets.html"><a href="tsets.html#tsets:demonstration:specification"><i class="fa fa-check"></i><b>4.6.1</b> The Specification Object</a></li>
<li class="chapter" data-level="4.6.2" data-path="tsets.html"><a href="tsets.html#tsets:demonstration:estimation"><i class="fa fa-check"></i><b>4.6.2</b> Estimation</a></li>
<li class="chapter" data-level="4.6.3" data-path="tsets.html"><a href="tsets.html#tsets:demonstration:prediction"><i class="fa fa-check"></i><b>4.6.3</b> Prediction</a></li>
<li class="chapter" data-level="4.6.4" data-path="tsets.html"><a href="tsets.html#tsets:demonstration:filtering"><i class="fa fa-check"></i><b>4.6.4</b> Filtering</a></li>
<li class="chapter" data-level="4.6.5" data-path="tsets.html"><a href="tsets.html#tsets:demonstration:simulation"><i class="fa fa-check"></i><b>4.6.5</b> Simulation</a></li>
<li class="chapter" data-level="4.6.6" data-path="tsets.html"><a href="tsets.html#tsets:demonstration:profiling"><i class="fa fa-check"></i><b>4.6.6</b> Profiling</a></li>
<li class="chapter" data-level="4.6.7" data-path="tsets.html"><a href="tsets.html#tsets:demonstration:backtesting"><i class="fa fa-check"></i><b>4.6.7</b> Backtesting</a></li>
<li class="chapter" data-level="4.6.8" data-path="tsets.html"><a href="tsets.html#tsets:demonstration:benchmarking"><i class="fa fa-check"></i><b>4.6.8</b> Benchmarking</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tsissm.html"><a href="tsissm.html"><i class="fa fa-check"></i><b>5</b> tsissm package</a><ul>
<li class="chapter" data-level="5.1" data-path="tsissm.html"><a href="tsissm.html#tsissm:introduction"><i class="fa fa-check"></i><b>5.1</b> Introduction</a></li>
<li class="chapter" data-level="5.2" data-path="tsissm.html"><a href="tsissm.html#tsissm:initialization"><i class="fa fa-check"></i><b>5.2</b> State Initialization</a></li>
<li class="chapter" data-level="5.3" data-path="tsissm.html"><a href="tsissm.html#tsissm:likelihood"><i class="fa fa-check"></i><b>5.3</b> Log-Likelihood</a></li>
<li class="chapter" data-level="5.4" data-path="tsissm.html"><a href="tsissm.html#tsissm:implementation"><i class="fa fa-check"></i><b>5.4</b> Package Implementation</a></li>
<li class="chapter" data-level="5.5" data-path="tsissm.html"><a href="tsissm.html#tsissm:demonstration"><i class="fa fa-check"></i><b>5.5</b> Demonstration</a><ul>
<li class="chapter" data-level="5.5.1" data-path="tsissm.html"><a href="tsissm.html#tsissm:demonstration:specification"><i class="fa fa-check"></i><b>5.5.1</b> Specification</a></li>
<li class="chapter" data-level="5.5.2" data-path="tsissm.html"><a href="tsissm.html#tsissm:demonstration:estimation"><i class="fa fa-check"></i><b>5.5.2</b> Estimation</a></li>
<li class="chapter" data-level="5.5.3" data-path="tsissm.html"><a href="tsissm.html#tsissm:demonstration:prediction"><i class="fa fa-check"></i><b>5.5.3</b> Prediction</a></li>
<li class="chapter" data-level="5.5.4" data-path="tsissm.html"><a href="tsissm.html#tsissm:demonstration:simulation"><i class="fa fa-check"></i><b>5.5.4</b> Simulation</a></li>
<li class="chapter" data-level="5.5.5" data-path="tsissm.html"><a href="tsissm.html#tsissm:demonstration:filtering"><i class="fa fa-check"></i><b>5.5.5</b> Filtering</a></li>
<li class="chapter" data-level="5.5.6" data-path="tsissm.html"><a href="tsissm.html#tsissm:demonstration:profiling"><i class="fa fa-check"></i><b>5.5.6</b> Profiling</a></li>
<li class="chapter" data-level="5.5.7" data-path="tsissm.html"><a href="tsissm.html#tsissm:demonstration:backtesting"><i class="fa fa-check"></i><b>5.5.7</b> Backtesting</a></li>
<li class="chapter" data-level="5.5.8" data-path="tsissm.html"><a href="tsissm.html#tsissm:demonstration:benchmarking"><i class="fa fa-check"></i><b>5.5.8</b> Benchmarking</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="tsvets.html"><a href="tsvets.html"><i class="fa fa-check"></i><b>6</b> tsvets package</a><ul>
<li class="chapter" data-level="6.1" data-path="tsvets.html"><a href="tsvets.html#tsvets:introduction"><i class="fa fa-check"></i><b>6.1</b> Introduction</a></li>
<li class="chapter" data-level="6.2" data-path="tsvets.html"><a href="tsvets.html#tsvets:regressors"><i class="fa fa-check"></i><b>6.2</b> Inclusion of External Regressors</a></li>
<li class="chapter" data-level="6.3" data-path="tsvets.html"><a href="tsvets.html#tsvets:likelihood"><i class="fa fa-check"></i><b>6.3</b> Log-Likelihood</a></li>
<li class="chapter" data-level="6.4" data-path="tsvets.html"><a href="tsvets.html#tsvets:dependence"><i class="fa fa-check"></i><b>6.4</b> Dependence Structure</a><ul>
<li class="chapter" data-level="6.4.1" data-path="tsvets.html"><a href="tsvets.html#tsvets:dependence:diagonal"><i class="fa fa-check"></i><b>6.4.1</b> Diagonal Covariance</a></li>
<li class="chapter" data-level="6.4.2" data-path="tsvets.html"><a href="tsvets.html#tsvets:dependence:equicorrelation"><i class="fa fa-check"></i><b>6.4.2</b> Equicorrelation</a></li>
<li class="chapter" data-level="6.4.3" data-path="tsvets.html"><a href="tsvets.html#tsvets:dependence:shrinkage"><i class="fa fa-check"></i><b>6.4.3</b> Shrinkage Covariance</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="tsvets.html"><a href="tsvets.html#tsvets:grouping"><i class="fa fa-check"></i><b>6.5</b> Grouping and Pooling</a></li>
<li class="chapter" data-level="6.6" data-path="tsvets.html"><a href="tsvets.html#tsvets:homogeneous"><i class="fa fa-check"></i><b>6.6</b> Homogeneous Coefficients and Aggregation</a></li>
<li class="chapter" data-level="6.7" data-path="tsvets.html"><a href="tsvets.html#tsvets:demonstration"><i class="fa fa-check"></i><b>6.7</b> Demonstration</a><ul>
<li class="chapter" data-level="6.7.1" data-path="tsvets.html"><a href="tsvets.html#tsvets:demonstration:specification"><i class="fa fa-check"></i><b>6.7.1</b> Specification</a></li>
<li class="chapter" data-level="6.7.2" data-path="tsvets.html"><a href="tsvets.html#tsvets:demonstration:example1"><i class="fa fa-check"></i><b>6.7.2</b> Example: Australian Retail Sales</a></li>
<li class="chapter" data-level="6.7.3" data-path="tsvets.html"><a href="tsvets.html#tsvets:demonstration:example2"><i class="fa fa-check"></i><b>6.7.3</b> Example: Australian Retail Sales Grouped Dynamics</a></li>
<li class="chapter" data-level="6.7.4" data-path="tsvets.html"><a href="tsvets.html#tsvets:demonstration:example3"><i class="fa fa-check"></i><b>6.7.4</b> Example: Australian Retail Sales Filtering</a></li>
<li class="chapter" data-level="6.7.5" data-path="tsvets.html"><a href="tsvets.html#tsvets:demonstration:example4"><i class="fa fa-check"></i><b>6.7.5</b> Example: Australian Retail Sales Aggregation</a></li>
<li class="chapter" data-level="6.7.6" data-path="tsvets.html"><a href="tsvets.html#tsvets:demonstration:example6"><i class="fa fa-check"></i><b>6.7.6</b> Example: Groupwise Pooling</a></li>
<li class="chapter" data-level="6.7.7" data-path="tsvets.html"><a href="tsvets.html#tsvets:demonstration:example5"><i class="fa fa-check"></i><b>6.7.7</b> Example: Price Volume Aggregation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="tsforeign.html"><a href="tsforeign.html"><i class="fa fa-check"></i><b>7</b> tsforeign package</a><ul>
<li class="chapter" data-level="7.1" data-path="tsforeign.html"><a href="tsforeign.html#tsforeign:introduction"><i class="fa fa-check"></i><b>7.1</b> Introduction</a></li>
<li class="chapter" data-level="7.2" data-path="tsforeign.html"><a href="tsforeign.html#tsforeign:arima"><i class="fa fa-check"></i><b>7.2</b> ARIMA model</a></li>
<li class="chapter" data-level="7.3" data-path="tsforeign.html"><a href="tsforeign.html#tsforeign:bsts"><i class="fa fa-check"></i><b>7.3</b> bsts model</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="tscausal.html"><a href="tscausal.html"><i class="fa fa-check"></i><b>8</b> tscausal package</a><ul>
<li class="chapter" data-level="8.1" data-path="tscausal.html"><a href="tscausal.html#tscausal:introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a></li>
<li class="chapter" data-level="8.2" data-path="tscausal.html"><a href="tscausal.html#tscausal:evalmeasures"><i class="fa fa-check"></i><b>8.2</b> Measures of Evaluation</a><ul>
<li class="chapter" data-level="8.2.1" data-path="tscausal.html"><a href="tscausal.html#tscausal:evalmeasures:pointwise"><i class="fa fa-check"></i><b>8.2.1</b> Pointwise Impact</a></li>
<li class="chapter" data-level="8.2.2" data-path="tscausal.html"><a href="tscausal.html#tscausal:evalmeasures:cumulative"><i class="fa fa-check"></i><b>8.2.2</b> Cumulative Impact</a></li>
<li class="chapter" data-level="8.2.3" data-path="tscausal.html"><a href="tscausal.html#tscausal:evalmeasures:meaneffect"><i class="fa fa-check"></i><b>8.2.3</b> Mean Effect</a></li>
<li class="chapter" data-level="8.2.4" data-path="tscausal.html"><a href="tscausal.html#tscausal:evalmeasures:relativeeffect"><i class="fa fa-check"></i><b>8.2.4</b> Mean Relative Effect</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="tscausal.html"><a href="tscausal.html#tscausal:significance"><i class="fa fa-check"></i><b>8.3</b> Evaluation of Significance</a></li>
<li class="chapter" data-level="8.4" data-path="tscausal.html"><a href="tscausal.html#tscausl:features"><i class="fa fa-check"></i><b>8.4</b> Package Features</a></li>
<li class="chapter" data-level="8.5" data-path="tscausal.html"><a href="tscausal.html#tscausl:demo"><i class="fa fa-check"></i><b>8.5</b> Package Demo</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="other.html"><a href="other.html"><i class="fa fa-check"></i><b>9</b> Other packages</a></li>
<li class="chapter" data-level="10" data-path="team.html"><a href="team.html"><i class="fa fa-check"></i><b>10</b> The tsmodels team</a></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://bookdown.org" target="_blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Time Series Framework</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tsets" class="section level1">
<h1><span class="header-section-number">Chapter 4</span> tsets package</h1>
<div id="tsets:intro" class="section level2">
<h2><span class="header-section-number">4.1</span> Introduction</h2>
<p>Exponential smoothing was proposed by Robert G. Brown, originally in <span class="citation">Brown (<a href="#ref-brown1959" role="doc-biblioref">1959</a>)</span> and later in <span class="citation">Brown (<a href="#ref-brown1962" role="doc-biblioref">1962</a>)</span>, where he developed the general exponential smoothing methodology in the context of inventory management, production planning and control. Independently, Charles C. Holt developed a similar method for exponential smoothing of additive trends and an entirely different method for smoothing seasonal data in <span class="citation">Holt (<a href="#ref-holt1957" role="doc-biblioref">1957</a>)</span>. This approach gained popularity following <span class="citation">Winters (<a href="#ref-winters1960" role="doc-biblioref">1960</a>)</span>, which tested Holt’s methods with empirical data, from whence the now popular Holt-Winters forecasting system came to prominence. More recently, <span class="citation">Hyndman et al. (<a href="#ref-hyndman2002" role="doc-biblioref">2002</a>)</span> and <span class="citation">Taylor (<a href="#ref-taylor2003" role="doc-biblioref">2003</a>)</span> formalized the framework and provided a taxonomy of the various models under different assumptions on the type of Error (E), Trend (T) and Seasonality (S) components.</p>
<p>In their most basic form, exponential smoothing methods are weighted sums of past observations, with the weights decaying exponentially with older observations. They form a simpler alternative to the more complex structural time series models (see <span class="citation">Harvey (<a href="#ref-harvey1990" role="doc-biblioref">1990</a>)</span> and <span class="citation">West and Harrison (<a href="#ref-west2006" role="doc-biblioref">2006</a>)</span>), by adopting the innovations formulation of the state space representation with all sources of error perfectly correlated.<a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a> The Single Source of Errors model is observationally equivalent to the Multiple Source of Errors model under non-restrictive assumptions, and the interested reader is referred to <span class="citation">Casals, Sotoca, and Jerez (<a href="#ref-casals1999" role="doc-biblioref">1999</a>)</span> for a proof of this.</p>
<p>Formally, the general linear innovations state space model can be written as:</p>
<p><span class="math display" id="eq:tsets1">\[\begin{equation}
\begin{array}{l}
{y_t} &amp;= {\bf{w&#39;}}{{\bf{x}}_{t - 1}} + {\varepsilon _t} ,\\
{{\bf{x}}_t} &amp;= {\bf{F}}{{\bf{x}}_{t - 1}} + {\bf{g}}{\varepsilon _t},
\end{array}
\tag{4.1}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(y_t\)</span> is the observed value at time <span class="math inline">\(t\)</span>, <span class="math inline">\(\mathbf{x}_t\)</span> the vector of state variables (which may include information about the level, slope, seasonal patterns and exogenous regressors), <span class="math inline">\(\mathbf{w}\)</span> is the observation matrix and <span class="math inline">\(\mathbf{F}\)</span> the state transition matrix. An innovations state space model can be reduced to an equivalent ARIMA model with the help of the lag operator <span class="math inline">\(L\)</span>. The state equation can be rewritten as:<a href="#fn6" class="footnote-ref" id="fnref6"><sup>6</sup></a></p>
<p><span class="math display" id="eq:tsets2">\[\begin{equation}
\left( {{\bf{I}} - {\bf{F}}L} \right){\mathbf{x}_t} = {\bf{g}}{\varepsilon _t}.
\tag{4.2}
\end{equation}\]</span></p>
<p>Since <span class="math inline">\({\bf{I}} - {\bf{F}}L\)</span> may not have an inverse, both sides are multiplied by its adjugate<a href="#fn7" class="footnote-ref" id="fnref7"><sup>7</sup></a> <span class="math inline">\(adj{\left( {{\bf{I}} - {\bf{F}}L} \right)}\)</span> to obtain:</p>
<p><span class="math display" id="eq:tsets3">\[\begin{equation}
\det\left( {{\bf{I}} - {\bf{F}}L} \right){\mathbf{x}_t} = adj{\left( {{\bf{I}} - {\bf{F}}L} \right)}{\bf{g}}{\varepsilon _t}.
\tag{4.3}
\end{equation}\]</span></p>
<p>Applying the <span class="math inline">\(\det\left( {{\bf{I}} - {\bf{F}}L} \right)\)</span> to the observation equation:</p>
<p><span class="math display" id="eq:tsets4">\[\begin{equation}
\det \left( {{\bf{I}} - {\bf{F}}L} \right){y_t} = {\bf{w&#39;}}\det \left( {{\bf{I}} - {\bf{F}}L} \right){{\mathbf{x}}_{t - 1}} + \det \left( {{\bf{I}} - {\bf{F}}L} \right){\varepsilon _t},
\tag{4.4}
\end{equation}\]</span></p>
<p>and finally replacing <span class="math inline">\(\det \left( {{\bf{I}} - {\bf{F}}L} \right){{\mathbf{x}}_{t - 1}}\)</span> with the state equation formula we obtain:</p>
<p><span class="math display" id="eq:tsets5">\[\begin{equation}
\det \left({\bf{I}} - {\bf{F}}L \right){y_t} = {\bf{w&#39;}}\det \left( {{\bf{I}} - {\bf{F}}L} \right){\bf{g}}{\varepsilon _{t - 1}} + \det \left( {{\bf{I}} - {\bf{F}}L} \right){\varepsilon _t}.
\tag{4.5}
\end{equation}\]</span></p>
<p>Defining <span class="math inline">\(\det \left( {{\bf{I}} - {\bf{F}}L} \right)\)</span> as <span class="math inline">\(\eta\left(L\right)\)</span> and <span class="math inline">\({\bf{w&#39;}}\det \left( {{\bf{I}} - {\bf{F}}L} \right){\bf{g}}{L} + \det \left( {{\bf{I}} - {\bf{F}}L} \right)\)</span> as <span class="math inline">\(\theta\left(L\right)\)</span> we obtain the typical ARIMA representation<a href="#fn8" class="footnote-ref" id="fnref8"><sup>8</sup></a> <span class="math inline">\(\eta \left( L \right){y_t} = \theta \left( L \right){\varepsilon _t}\)</span>, where <span class="math inline">\(\eta\left(L\right)\)</span> and <span class="math inline">\(\theta\left(L\right)\)</span> are polynomials in the lag operator <span class="math inline">\(L\)</span> and may include powers of <span class="math inline">\(L\)</span> related to the seasonal period <span class="math inline">\(m\)</span>. To obtain the ARIMA representation, set <span class="math inline">\(\eta \left( L \right){y_t} = \phi \left( L \right)\delta \left( L \right){y_t}\)</span>, where <span class="math inline">\(\delta\left(L\right)\)</span> contains all unit roots of the polynomial.</p>
<p>Typical examples include the damped local trend model,<a href="#fn9" class="footnote-ref" id="fnref9"><sup>9</sup></a> which can be represented by an ARIMA(1,1,2) model and the local linear trend model, which can be represented as an ARIMA(0,2,2) model. On the other hand, an ARIMA(2,0,2) model with complex roots, which gives rise to cyclical behavior, cannot be represented by an exponential smoothing model.</p>
</div>
<div id="tsets:taxonomy" class="section level2">
<h2><span class="header-section-number">4.2</span> Taxonomy of Models</h2>
<p>Table <a href="tsets.html#tab:taxonomy">4.1</a> presents the taxonomy proposed by <span class="citation">Pegels (<a href="#ref-pegels" role="doc-biblioref">1969</a>)</span> and <span class="citation">Gardner Jr (<a href="#ref-gardner1985" role="doc-biblioref">1985</a>)</span> for exponential smoothing models. In addition, for each of the 12 model combinations presented, it is possible to have either additive or multiplicative errors, giving rise to the <strong>ETS</strong> formulation of <strong>E</strong>rror, <strong>T</strong>rend and <strong>S</strong>easonal. For instance, the <strong>MAM</strong> model corresponds to Multiplicative Error, Additive Trend and Multiplicative Seasonality.</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:taxonomy">TABLE 4.1: </span>Exponential Smoothing Model Taxonomy
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:center;">
N
</th>
<th style="text-align:center;">
A
</th>
<th style="text-align:center;">
M
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
</td>
<td style="text-align:center;">
(none)
</td>
<td style="text-align:center;">
(additive)
</td>
<td style="text-align:center;">
(multiplicative)
</td>
</tr>
<tr>
<td style="text-align:left;">
N (none)
</td>
<td style="text-align:center;">
NN
</td>
<td style="text-align:center;">
NA
</td>
<td style="text-align:center;">
NM
</td>
</tr>
<tr>
<td style="text-align:left;">
A (additive)
</td>
<td style="text-align:center;">
AN
</td>
<td style="text-align:center;">
AA
</td>
<td style="text-align:center;">
AM
</td>
</tr>
<tr>
<td style="text-align:left;">
M (multiplicative)
</td>
<td style="text-align:center;">
MN
</td>
<td style="text-align:center;">
MA
</td>
<td style="text-align:center;">
MM
</td>
</tr>
<tr>
<td style="text-align:left;">
D (damped)
</td>
<td style="text-align:center;">
DN
</td>
<td style="text-align:center;">
DA
</td>
<td style="text-align:center;">
DM
</td>
</tr>
</tbody>
</table>
<p>Following <span class="citation">Ord, Koehler, and Snyder (<a href="#ref-ord1997" role="doc-biblioref">1997</a>)</span> and <span class="citation">Hyndman et al. (<a href="#ref-hyndman2002" role="doc-biblioref">2002</a>)</span>, we present a state space formulation the ETS modelling system.</p>
<p><span class="math display" id="eq:tsets6">\[\begin{equation}
\begin{array}{l}
{y_t} = h\left( {{\mathbf{x}_{t - 1}}} \right) + k\left( {{\mathbf{x}_{t - 1}}} \right){\varepsilon _t},\\
{\mathbf{x}_t} = f\left( {{\mathbf{x}_{t - 1}}} \right) + g\left( {{\mathbf{x}_{t - 1}}} \right){\varepsilon _t},
\end{array}
\tag{4.6}
\end{equation}\]</span></p>
<p>where <span class="math inline">\({\varepsilon _t} \sim N\left( {0,{\sigma ^2}} \right)\)</span> and <span class="math inline">\({\mathbf{x}_t} = \left\{ {{l_t},{b_t},{s_{t - 1}},...,{s_{t - \left( {m - 1} \right)}}} \right\}\)</span>. Defining <span class="math inline">\({e_t} = k\left( {{x_{t - 1}}} \right){\varepsilon _t}\)</span> and <span class="math inline">\({\mu _t} = h\left( {{x_{t - 1}}} \right)\)</span>, then <span class="math inline">\({y_t} = {\mu _t} + {e_t}\)</span>. When errors are additive, then <span class="math inline">\(y_t=\mu_t + \varepsilon_t\)</span> and <span class="math inline">\(k\left( {{x_{t - 1}}} \right)=1\)</span>, whilst when errors are multiplicative, then <span class="math inline">\(y_t=\mu_t\left(1+\varepsilon_t\right)\)</span> and therefore <span class="math inline">\(k\left( {{x_{t - 1}}} \right)=\mu_t\)</span> so that <span class="math inline">\(\varepsilon_t=\frac{\left(y_t-\mu_t\right)}{\mu_t}\)</span> represents a relative error. For illustration, we show below the additive error with additive trend and seasonality:</p>
<p><span class="math display" id="eq:tsets7">\[\begin{equation}
\begin{array}{l}
{{\hat y}_t} = {l_{t - 1}} + \phi {b_{t - 1}} + {s_{t - m}},\\
{\varepsilon _t} = {y_t} - {{\hat y}_t},\\
{l_t} = {l_{t - 1}} + \phi {b_{t - 1}} + \alpha {\varepsilon _t},\\
{b_t} = \phi {b_{t - 1}} + \beta {\varepsilon _t},\\
{s_t} = {s_{t - m}} + \gamma {\varepsilon _t},
\end{array}
\tag{4.7}
\end{equation}\]</span></p>
<p>with <span class="math inline">\(\phi\)</span> representing the damping parameter which is equal to one when there is no damping. The <span class="math inline">\(h\)</span>-step ahead forecast is then given as:</p>
<p><span class="math display" id="eq:tsets8">\[\begin{equation}
{y_{t + h}} = \left\{ {\begin{array}{*{20}{c}}
{{l_t} + h{b_t} + {s_{t - m + h_m^ + }}},&amp;{\phi \in \left\{ \emptyset \right\}},\\
{{l_t} + {\phi^h}{b_t} + {s_{t - m + h_m^ + }}},&amp;{\phi \in [0,1]},
\end{array}} \right.
\tag{4.8}
\end{equation}\]</span></p>
<p>where <span class="math inline">\(h_m^ + = \left[ {\left( {h - 1} \right)\bmod m} \right] + 1\)</span>.</p>
</div>
<div id="tsets:extensions" class="section level2">
<h2><span class="header-section-number">4.3</span> Extensions</h2>
<p>A number of extensions have been suggested and too numerous to outline here. One interesting model proposed by <span class="citation">Koehler, Snyder, and Ord (<a href="#ref-koehler2001" role="doc-biblioref">2001</a>)</span> is the decomposition of the MAM model to include power terms as follows:</p>
<p><span class="math display" id="eq:tsets9">\[\begin{equation}
\begin{array}{l}
{y_t} = \left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right){s_{t - m}} + {\left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right)^\theta }{s^\delta }_{t - m}{\varepsilon _t},\\
{l_t} = \left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right) + \alpha {\left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right)^\theta }{s_{t - m}^{\delta  - 1}}{\varepsilon _t},\\
{b_t} = \phi {b_{t - 1}} + \beta {\left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right)^\theta }{s_{t - m}^{\delta  - 1}}{\varepsilon _t},\\
{s_t} = {s_{t - m}} + \gamma {\left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right)^{\theta  - 1}}{s_{t - m}^\delta}{\varepsilon _t}.
\end{array}
\tag{4.9}
\end{equation}\]</span></p>
<p>When <span class="math inline">\(\theta=1\)</span> and <span class="math inline">\(\delta=1\)</span>, this reduces to the standard MAM model. When <span class="math inline">\(\theta=0\)</span> and <span class="math inline">\(\delta=0\)</span> this is reduces to the AAM model or the AAN model if there is no seasonal term. The exponents can be thought as controlling the degree of heteroscedasticity in the data, since the unscaled residuals <span class="math inline">\(\epsilon_t\)</span> are distributed as:</p>
<p><span class="math display" id="eq:tsets10">\[\begin{equation}
{\epsilon_t} = {y_t} - \left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right){s_{t - m}},\quad {\epsilon_t} | \mathcal{F}_{t-1} \sim N\left( {0,{{\left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right)}^{2\theta} }{s_{t-m}^{2\delta}} \sigma^2 } \right),
\tag{4.10}
\end{equation}\]</span></p>
<p>which is an appealing alternative to Box Cox and related transformations. For instance, as <span class="citation">R. Hyndman et al. (<a href="#ref-hyndman2008" role="doc-biblioref">2008</a>)</span> 4.4.5 notes, a value of <span class="math inline">\(\theta=1/3\)</span> would produce a variance proportional to the <span class="math inline">\(2/3\)</span> power of the mean, similar to the cube root transformation.</p>
<p>Normalized seasonality, discussed in <span class="citation">Roberts (<a href="#ref-roberts1982" role="doc-biblioref">1982</a>)</span> and <span class="citation">McKenzie (<a href="#ref-mckenzie1986" role="doc-biblioref">1986</a>)</span>, can be used to de-seasonalize the data, by acting as a filter, and is required for implementing the Wiener-Kolmogorov (WK) filter (smoother). This is discussed in more detail in Chapter 8 of <span class="citation">R. Hyndman et al. (<a href="#ref-hyndman2008" role="doc-biblioref">2008</a>)</span>, and is implemented as an option in the <strong>tsets</strong> package.</p>
<p>Another avenue of interest is in the multivariate generalization of the model presented in <span class="citation">De Silva, Hyndman, and Snyder (<a href="#ref-desilva2010" role="doc-biblioref">2010</a>)</span>. It has the ability to incorporate common levels, trends or seasonality and is implemented in the <strong>tsvets</strong> package.</p>
</div>
<div id="some-encompasing-alternatives" class="section level2">
<h2><span class="header-section-number">4.4</span> Some Encompasing Alternatives</h2>
<p>The general state space representation (see <span class="citation">Harvey (<a href="#ref-harvey1990" role="doc-biblioref">1990</a>)</span>), based on the multiple sources of error (MSOE) state space model, provides a more general implementation of the unobserved components model, albeit requiring the use of the Kalman filter for estimation. The model is flexible enough to incorporate many types of additive models, including cyclical behavior and regressors, although the nonlinear (multiplicative) variations require the extended Kalman filter for estimation. The <a href="https://cran.r-project.org/web/packages/bsts/"><strong>bsts</strong></a> package of <span class="citation">Scott and Varian (<a href="#ref-scott2015" role="doc-biblioref">2015</a>)</span> provides fast and efficient computation of Bayesian Unobserved Components, with the option of a spike and slab prior for regressor regularization, for which we provide a wrapper in the <strong>tsforeign</strong> package.</p>
</div>
<div id="tsets:implementation" class="section level2">
<h2><span class="header-section-number">4.5</span> Package Implementation</h2>
<p>The <strong>tsets</strong> package implements 4 families of models, whose equations are given in Tables <a href="tsets.html#tab:models1">4.2</a> and <a href="tsets.html#tab:models2">4.3</a>. These are the full equations assuming all variables (trend, damped, seasonal and regressors) enter the model, but any and all combinations of the variables are allowed. Methods implemented include Quasi-ML estimation, prediction, simulation, plotting and post-estimation diagnostics.</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:models1">TABLE 4.2: </span>AAA and MMM Model Equations
</caption>
<thead>
<tr>
<th style="text-align:left;">
Equation
</th>
<th style="text-align:center;">
AAA
</th>
<th style="text-align:center;">
MMM
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Observation
</td>
<td style="text-align:center;">
<span class="math inline">\({y_t} = {l_{t - 1}} + \phi{b_{t - 1}} + {s_{t - m}} + \bf{x}_{t - 1}\bf{w} + \varepsilon_t\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({y_t} = {l_{t - 1}}{b_{t-1}^\phi}\left(\bf{x}_{t-1}\bf{w}\right){s_{t - m}}\left(1 + \varepsilon _t\right)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Mean
</td>
<td style="text-align:center;">
<span class="math inline">\({\mu _t} = {l_{t - 1}} + \phi{b_{t - 1}} + {s_{t - m}} + {{\bf{x}}_{t - 1}}{\bf{w}}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({\mu_t} = {l_{t - 1}}{b^\phi_{t - 1}}\left( {{{\bf{x}}_{t-1}}{\bf{w}}} \right){s_{t - m}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Distribution
</td>
<td style="text-align:center;">
<span class="math inline">\({\hat y_t}\left| {{\Im _{t - 1}} \sim N\left( {{\mu _t},\sigma } \right)} \right.\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({{\hat y}_t}\left| {{\Im _{t - 1}} \sim N\left( {{\mu _t},{l_{t - 1}}{b_{t-1}^\phi}\left( {{{\bf{x}}_{t-1}}{\bf{w}}} \right){s_{t - m}}\sigma } \right)} \right.\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Error
</td>
<td style="text-align:center;">
<span class="math inline">\({\varepsilon _t} = {y_t} - {\mu _t}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({\varepsilon _t} = \frac{{{y_t} - {\mu _t}}}{{{l_{t - 1}}{b}_{t - 1}^\phi \left( {{{\bf{x}}_{t-1}}{\bf{w}}} \right){s_{t - m}}}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Level[State]
</td>
<td style="text-align:center;">
<span class="math inline">\({l_t} = {l_{t - 1}} + \phi {b_{t - 1}} + \alpha {\varepsilon _t}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({l_t} = {l_{t - 1}}{b_{t-1}^\phi}\left( {1 + \alpha {\varepsilon _t}} \right)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Trend[State]
</td>
<td style="text-align:center;">
<span class="math inline">\({b_t} = \phi {b_{t - 1}} + \beta {\varepsilon _t}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({b_t} = {b_{t-1}^\phi}\left( {1 + \beta {\varepsilon _t}} \right)\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Seasonal[State]
</td>
<td style="text-align:center;">
<span class="math inline">\({s_t} = {s_{t - m}} + \gamma {\varepsilon _t}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({s_t} = {s_{t - m}}\left( {1 + \gamma {\varepsilon _t}} \right)\)</span>
</td>
</tr>
</tbody>
</table>
<table class="table table-striped table-hover table-condensed table-responsive" style="font-size: 11px; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:models2">TABLE 4.3: </span>MAM and powerMAM Model Equations
</caption>
<thead>
<tr>
<th style="text-align:left;">
Equation
</th>
<th style="text-align:center;">
MAM
</th>
<th style="text-align:center;">
powerMAM
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Observation
</td>
<td style="text-align:center;">
<span class="math inline">\({y_t} = \left( {{l_{t - 1}} + \phi {b_{t - 1}} + {{\bf{x}}_{t - 1}}{\bf{w}}} \right){s_{t - m}}\left( {1 + {\varepsilon _t}} \right)\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({y_t} = \left( {{l_{t - 1}} + \phi {b_{t - 1}} + {{\bf{x}}_{t - 1}}{\bf{w}}} \right){s_{t - m}} + {\left( {{l_{t - 1}} + \phi {b_{t - 1}} + {{\bf{x}}_{t - 1}}{\bf{w}}} \right)^\theta }s_{t - m}^\delta {\varepsilon _t}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Mean
</td>
<td style="text-align:center;">
<span class="math inline">\({\mu _t} = \left( {{l_{t - 1}} + \phi {b_{t - 1}} + {{\bf{x}}_{t - 1}}{\bf{w}}} \right){s_{t - m}}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({\mu _t} = \left( {{l_{t - 1}} + \phi {b_{t - 1}} + {{\bf{x}}_{t - 1}}{\bf{w}}} \right){s_{t - m}}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Distribution
</td>
<td style="text-align:center;">
<span class="math inline">\({\hat y_t}\left| {{\Im _{t - 1}} \sim N\left( {{\mu _t},\left( {{l_{t - 1}} + \phi {b_{t - 1}} + {{\bf{x}}_{t - 1}}{\bf{w}}} \right){s_{t - m}}\sigma } \right)} \right.\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({\hat y_t}\left| {{\Im _{t - 1}} \sim N\left( {{\mu _t},{{\left( {{l_{t - 1}} + \phi {b_{t - 1}} + {{\bf{x}}_{t - 1}}{\bf{w}}} \right)}^\theta }s_{t - m}^\delta \sigma } \right)} \right.\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Error
</td>
<td style="text-align:center;">
<span class="math inline">\({\varepsilon _t} = \frac{{{y_t} - {\mu _t}}}{{\left( {{l_{t - 1}} + \phi {b_{t - 1}} + {{\bf{x}}_{t - 1}}{\bf{w}}} \right){s_{t - m}}}}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({\varepsilon _t} = \frac{{{y_t} - {\mu _t}}}{{{{\left( {{l_{t - 1}} + \phi {b_{t - 1}} + {{\bf{x}}_{t - 1}}{\bf{w}}} \right)}^\theta }s_{t - m}^\delta }}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Level[State]
</td>
<td style="text-align:center;">
<span class="math inline">\({l_t} = \left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right)\left( {1 + \alpha {\varepsilon _t}} \right)\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({l_t} = \left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right) + \alpha {\left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right)^\theta }s_{t - m}^{\delta - 1}{\varepsilon _t}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Trend[State]
</td>
<td style="text-align:center;">
<span class="math inline">\({b_t} = \phi {b_{t - 1}} + \beta \left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right){\varepsilon _t}\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({b_t} = \phi {b_{t - 1}} + \beta {\left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right)^\theta }s_{t - m}^{\delta - 1}{\varepsilon _t}\)</span>
</td>
</tr>
<tr>
<td style="text-align:left;">
Seasonal[State]
</td>
<td style="text-align:center;">
<span class="math inline">\({s_t} = {s_{t - m}}\left( {1 + \gamma {\varepsilon _t}} \right)\)</span>
</td>
<td style="text-align:center;">
<span class="math inline">\({s_t} = {s_{t - m}} + \gamma {\left( {{l_{t - 1}} + \phi {b_{t - 1}}} \right)^{\theta - 1}}s_{t - m}^\delta {\varepsilon _t}\)</span>
</td>
</tr>
</tbody>
</table>
<div id="tsets:implementation:constraints" class="section level3">
<h3><span class="header-section-number">4.5.1</span> Constraints</h3>
<p>Variables in the additive ETS type models need to be constrained in order to achieve stability and forecastability, and the interested reader should consult Section 10.2 of <span class="citation">R. J. Hyndman, Akram, and Archibald (<a href="#ref-hyndman2008a" role="doc-biblioref">2008</a>)</span> for more details. These conditions become increasingly complex depending on the components included in the model. In our implementation we have opted for the following simple conditions:</p>
<ul>
<li><span class="math inline">\(\alpha \in \left[ {0,1} \right]\)</span>,</li>
<li><span class="math inline">\(\beta \in \left[ {0,\alpha } \right]\)</span>,</li>
<li><span class="math inline">\(\gamma \in \left[ {0,1 - \alpha } \right]\)</span>,</li>
<li><span class="math inline">\(\phi \in \left[ {0.5,1} \right]\)</span>,</li>
<li><span class="math inline">\(\theta \in \left[ {0,1} \right]\)</span>,</li>
<li><span class="math inline">\(\delta \in \left[ {0,1} \right]\)</span>,</li>
<li><span class="math inline">\(\sigma \in {{\bf{R}}_+ }\)</span>.</li>
</ul>
<p>For multiplicative models, we simply impose that <span class="math inline">\(\max\left(\alpha,\beta,\gamma\right)&lt;1\)</span> and <span class="math inline">\(\varepsilon_t&gt;-1\)</span>, although we do not impose the last condition for estimation (only for simulation).</p>
</div>
<div id="tsets:implementation:initialization" class="section level3">
<h3><span class="header-section-number">4.5.2</span> Initialization</h3>
<p>To obtain a reasonable set of parameters for the initialization conditions of the states as well as the parameters, we obtain values for <span class="math inline">\(l_0\)</span>, <span class="math inline">\(b_0\)</span> and <span class="math inline">\(s_0\)</span> using the heuristic approach described in Section 5.2 of <span class="citation">R. Hyndman et al. (<a href="#ref-hyndman2008" role="doc-biblioref">2008</a>)</span>. There is also an option for estimating the initial states for the seasonal component.</p>
</div>
<div id="tsets:implementation:transformations" class="section level3">
<h3><span class="header-section-number">4.5.3</span> Transformations</h3>
<p>Variance stabilizing transformations form an important part of the pre-processing of the outcome variable in order to achieve certain statistical properties which help reduce misspecification of the model. At present, we implement the Box-Cox transformation with an option for automatic tuning of the parameter <span class="math inline">\(\lambda\)</span> using the method of <span class="citation">Guerrero (<a href="#ref-guerrero1993time" role="doc-biblioref">1993</a>)</span>, from the <strong>tsaux</strong> package.</p>
</div>
</div>
<div id="tsets:demonstration" class="section level2">
<h2><span class="header-section-number">4.6</span> Demonstration</h2>
<div id="tsets:demonstration:specification" class="section level3">
<h3><span class="header-section-number">4.6.1</span> The Specification Object</h3>
<p>The entry specification function is called <code>ets_modelspec</code></p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="tsets.html#cb11-1"></a><span class="kw">suppressWarnings</span>(<span class="kw">suppressMessages</span>(<span class="kw">library</span>(tsets)))</span>
<span id="cb11-2"><a href="tsets.html#cb11-2"></a><span class="kw">args</span>(ets_modelspec)</span></code></pre></div>
<pre><code>## function (y, model = &quot;AAN&quot;, damped = FALSE, power = FALSE, xreg = NULL, 
##     frequency = NULL, lambda = NULL, normalized_seasonality = TRUE, 
##     fixed_pars = NULL, scale = FALSE, seasonal_init = &quot;fixed&quot;, 
##     lambda_lower = 0, lambda_upper = 1, sampling = NULL, ...) 
## NULL</code></pre>
<p>This requires passing in an <code>xts</code> vector <code>y</code>, followed by a number of options described below:</p>
<ul>
<li><code>model</code>: The ETS model type.</li>
<li><code>damped</code>: Whether to dampen the trend.</li>
<li><code>power</code>: The power MAM model (only applicable to the MAM).</li>
<li><code>xreg</code>: An <code>xts</code> matrix of regressors.</li>
<li><code>frequency</code>: The seasonal frequency of <code>y</code>, only needed if using a seasonal model.</li>
<li><code>lambda</code>: The Box Box transformation parameter. If <code>NA</code>, will estimate it.</li>
<li><code>normalized_seasonality</code>: Whether to impose the normalized approach of <span class="citation">McKenzie (<a href="#ref-mckenzie1986" role="doc-biblioref">1986</a>)</span>.</li>
<li><code>fixed_pars</code>: An optional named vector of fixed parameters.</li>
<li><code>scale</code>: Whether to pre-scale the data prior to estimation (will rescale back after estimation).</li>
<li><code>seasonal_init</code>: Whether to “estimate” or use the heuristic (“fixed”) values for the initial states.</li>
<li><code>sampling</code>: An optional string denoting the sampling frequency of the data (will try to discover it if <code>NULL</code>).</li>
</ul>
</div>
<div id="tsets:demonstration:estimation" class="section level3">
<h3><span class="header-section-number">4.6.2</span> Estimation</h3>
<p>For illustration, we use the <code>gas</code> dataset from the <strong>tsdatasets</strong> package, representing weekly US finished motor gasoline products supplied (in thousands of barrels per day) from February 1991 to May 2005.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="tsets.html#cb13-1"></a><span class="kw">data</span>(gas, <span class="dt">package =</span> <span class="st">&quot;tsdatasets&quot;</span>)</span>
<span id="cb13-2"><a href="tsets.html#cb13-2"></a>spec &lt;-<span class="st"> </span><span class="kw">ets_modelspec</span>(gas[<span class="dv">1</span><span class="op">:</span>(<span class="kw">NROW</span>(gas) <span class="op">-</span><span class="st"> </span><span class="dv">52</span>)], <span class="dt">model =</span> <span class="st">&quot;AAA&quot;</span>, <span class="dt">frequency =</span> <span class="dv">52</span>, </span>
<span id="cb13-3"><a href="tsets.html#cb13-3"></a>                      <span class="dt">lambda =</span> <span class="ot">NA</span>)</span>
<span id="cb13-4"><a href="tsets.html#cb13-4"></a><span class="kw">str</span>(spec, <span class="dt">max.level =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## List of 5
##  $ target   :List of 6
##  $ model    :List of 14
##  $ seasonal :List of 1
##  $ transform:List of 3
##  $ xreg     :List of 3
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;tsets.spec&quot; &quot;tsmodel.spec&quot;</code></pre>
<p>The specification object returns a list which inherits the <code>tsmodel.spec</code> class and has a number of slots. Common across the <strong>tsmodels</strong> framework will be the <code>target</code> slot, which has the target variable with details on its sampling frequency among others, the <code>transform</code> slot, which contains the Box Cox transformation and its inverse, and the <code>xreg</code> slot, which contains any optionally including external regressors.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="tsets.html#cb15-1"></a>mod &lt;-<span class="st"> </span><span class="kw">estimate</span>(spec)</span>
<span id="cb15-2"><a href="tsets.html#cb15-2"></a><span class="co"># automatic selection</span></span>
<span id="cb15-3"><a href="tsets.html#cb15-3"></a><span class="co"># mod_auto &lt;- auto_ets(gas[1:(NROW(gas) - 52)], frequency = 52, lambda = NA, </span></span>
<span id="cb15-4"><a href="tsets.html#cb15-4"></a><span class="co">#                      metric = &quot;MSLRE&quot;, cores = 4)</span></span>
<span id="cb15-5"><a href="tsets.html#cb15-5"></a><span class="kw">summary</span>(mod)</span></code></pre></div>
<pre><code>## 
## ETS Model [ AAA ]
## 
## Param  Description                     Est[Value]
## ------------------------------------------------                                                
##  alpha State[Level-coef]               3.453e-02
##  beta  State[Slope-coef]               1.000e-04
##  gamma State[Seasonal-coef]            0.000e+00
##  l0    State[Level-init]               7.108e+03
##  b0    State[Slope-init]               2.762e+00
##  sigma Observation[Standard Deviation] 2.621e+02
## 
##  AIC      BIC      AICc    
##  12364.03 12622.87 12374.44
## 
##  MAPE   MASE   MSLRE  BIAS 
##  0.0262 0.6369 0.0011 9e-04</code></pre>
<p>A number of methods exist for post-estimation inference which we illustrate below.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="tsets.html#cb17-1"></a><span class="kw">logLik</span>(mod)</span></code></pre></div>
<pre><code>## &#39;log Lik.&#39; -6125.014 (df=6)</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="tsets.html#cb19-1"></a><span class="kw">AIC</span>(mod)</span></code></pre></div>
<pre><code>## [1] 12364.03</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="tsets.html#cb21-1"></a><span class="kw">coef</span>(mod)</span></code></pre></div>
<pre><code>##         alpha          beta         gamma            l0            b0 
##    0.03453123    0.00010000    0.00000000 7107.77952558    2.76244932 
##            s0            s1            s2            s3            s4 
## -506.79631332 -447.01230297 -476.68115042 -131.08931857  -75.93870995 
##            s5            s6            s7            s8            s9 
##  143.22584577   46.91957489   43.84601545 -181.85203203 -122.91905990 
##           s10           s11           s12           s13           s14 
##  -40.83137039  103.34065156   62.24143451   58.63763652  132.14003123 
##           s15           s16           s17           s18           s19 
##   59.26762186  -31.24376860 -111.26657179   32.98945507   80.23597147 
##           s20           s21           s22           s23           s24 
##  168.50761693  317.79677244  249.90941754  359.85242961  244.12706217 
##           s25           s26           s27           s28           s29 
##  407.14465533  203.11825390  351.43412704  234.96291063  362.88019416 
##           s30           s31           s32           s33           s34 
##  323.72973094  240.69933477   46.86023690   50.98268170   76.04708428 
##           s35           s36           s37           s38           s39 
##  186.30912129   45.32728297  -17.11459876 -162.83816007  160.46100413 
##           s40           s41           s42           s43           s44 
##  -55.24277755 -142.44683934 -168.46179046 -133.42406098  -90.89932875 
##           s45           s46           s47           s48           s49 
##   -1.46974286 -278.23593662 -266.81064348 -225.95612406 -232.58290454 
##           s50         sigma 
## -478.24412479  262.06262972</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="tsets.html#cb23-1"></a><span class="kw">head</span>(<span class="kw">residuals</span>(mod, <span class="dt">raw =</span> <span class="ot">TRUE</span>))</span></code></pre></div>
<pre><code>##             residuals
## 1991-02-01  -80.31776
## 1991-02-08 -203.58198
## 1991-02-15 -296.03378
## 1991-02-22  346.48235
## 1991-03-01   23.83767
## 1991-03-08  103.65627</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="tsets.html#cb25-1"></a><span class="kw">head</span>(<span class="kw">residuals</span>(mod, <span class="dt">raw =</span> <span class="ot">FALSE</span>))</span></code></pre></div>
<pre><code>##             residuals
## 1991-02-01  -80.36452
## 1991-02-08 -203.70024
## 1991-02-15 -296.20633
## 1991-02-22  346.68537
## 1991-03-01   23.85160
## 1991-03-08  103.71685</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="tsets.html#cb27-1"></a><span class="kw">head</span>(<span class="kw">fitted</span>(mod))</span></code></pre></div>
<pre><code>##              fitted
## 1991-02-01 6701.365
## 1991-02-08 6636.700
## 1991-02-15 6878.206
## 1991-02-22 6877.315
## 1991-03-01 6851.148
## 1991-03-08 6843.283</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="tsets.html#cb29-1"></a><span class="kw">plot</span>(mod)</span></code></pre></div>
<p><img src="tsmodels_files/figure-html/inference-1.png" width="768" /></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="tsets.html#cb30-1"></a><span class="kw">tsdiagnose</span>(mod)</span></code></pre></div>
<pre><code>## 
## Weighted Ljung-Box Test [scaled residuals]
## ------------------------------------------
##  Lag statistic  pvalue
##  [1]      9.09 0.00256
##  [2]      9.44 0.00269
##  [3]     10.79 0.00195
##  [4]     11.49 0.00220
## 
## Parameter Bounds and Conditions
## ------------------------------------------
##   coef  value  &gt;lb  &lt;ub      condition condition_pass
##  alpha 0.0345 TRUE TRUE             NA             NA
##   beta 0.0001 TRUE TRUE        &lt; alpha           TRUE
##  gamma 0.0000 TRUE TRUE  &lt; (1 - alpha)           TRUE
##    phi     NA TRUE TRUE             NA             NA
##  theta     NA TRUE TRUE             NA             NA
##  delta     NA TRUE TRUE             NA             NA
## 
## Outlier Diagnostics (based on Rosner Test)
## ------------------------------------------
## Outliers: 1998-03-27</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="tsets.html#cb32-1"></a><span class="kw">tsmetrics</span>(mod)</span></code></pre></div>
<pre><code>##     n no.pars    LogLik      AIC      BIC     AICc       MAPE     MASE
## 1 693      56 -6125.014 12364.03 12622.87 12374.44 0.02621505 0.636897
##         MSLRE         BIAS
## 1 0.001093048 0.0008632586</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="tsets.html#cb34-1"></a>tsd_mod &lt;-<span class="st"> </span><span class="kw">tsdecompose</span>(mod)</span>
<span id="cb34-2"><a href="tsets.html#cb34-2"></a>tsd_mod &lt;-<span class="st"> </span><span class="kw">do.call</span>(cbind, <span class="kw">lapply</span>(<span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(tsd_mod), <span class="cf">function</span>(i) tsd_mod[[i]]))</span>
<span id="cb34-3"><a href="tsets.html#cb34-3"></a><span class="kw">head</span>(tsd_mod)</span></code></pre></div>
<pre><code>##              fitted  Residuals    Level    Slope    Seasonal
## 1991-02-01 6701.365  -80.31776 7107.769 2.754418 -478.244125
## 1991-02-08 6636.700 -203.58198 7103.493 2.734059 -232.582905
## 1991-02-15 6878.206 -296.03378 7096.005 2.704456 -225.956124
## 1991-02-22 6877.315  346.48235 7110.674 2.739104 -266.810643
## 1991-03-01 6851.148   23.83767 7114.236 2.741488 -278.235937
## 1991-03-08 6843.283  103.65627 7120.557 2.751854   -1.469743</code></pre>
</div>
<div id="tsets:demonstration:prediction" class="section level3">
<h3><span class="header-section-number">4.6.3</span> Prediction</h3>
<p>All prediction objects in the tsmodels framework are of class <code>tsmodel.predict</code>, with slots for the original series and the forecast distribution (the latter being of class <code>tsmodel.distribution</code>). Some prediction objects will contain additional slots, usually the original specification object as well as the state component predicted decomposition (also of class <code>tsmodel.distribution</code>).</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="tsets.html#cb36-1"></a>p &lt;-<span class="st"> </span><span class="kw">predict</span>(mod, <span class="dt">h =</span> <span class="dv">52</span>, <span class="dt">nsim =</span> <span class="dv">5000</span>)</span>
<span id="cb36-2"><a href="tsets.html#cb36-2"></a><span class="kw">class</span>(p)</span></code></pre></div>
<pre><code>## [1] &quot;tsets.predict&quot;   &quot;tsmodel.predict&quot;</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="tsets.html#cb38-1"></a><span class="kw">str</span>(p, <span class="dt">max.level =</span> <span class="dv">1</span>)</span></code></pre></div>
<pre><code>## List of 6
##  $ distribution   : &#39;tsets.distribution&#39; num [1:5000, 1:52] 9362 8703 8938 9120 9283 ...
##   ..- attr(*, &quot;dimnames&quot;)=List of 2
##   ..- attr(*, &quot;date_class&quot;)= chr &quot;Date&quot;
##  $ original_series:&#39;zoo&#39; series from 1991-02-01 to 2004-05-07
##   Data: num [1:693] 6621 6433 6582 7224 6875 ...
##   Index:  Date[1:693], format: &quot;1991-02-01&quot; &quot;1991-02-08&quot; ...
##  $ h              : num 52
##  $ spec           :List of 5
##   ..- attr(*, &quot;class&quot;)= chr [1:2] &quot;tsets.spec&quot; &quot;tsmodel.spec&quot;
##  $ decomposition  :List of 6
##  $ mean           :&#39;zoo&#39; series from 2004-05-14 to 2005-05-06
##   Data: Named num [1:52] 9147 9125 9126 9316 9403 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:52] &quot;2004-05-14&quot; &quot;2004-05-21&quot; &quot;2004-05-28&quot; &quot;2004-06-04&quot; ...
##   Index:  Date[1:52], format: &quot;2004-05-14&quot; &quot;2004-05-21&quot; ...
##  - attr(*, &quot;class&quot;)= chr [1:2] &quot;tsets.predict&quot; &quot;tsmodel.predict&quot;</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="tsets.html#cb40-1"></a><span class="kw">plot</span>(p, <span class="dt">n_original =</span> <span class="dv">52</span><span class="op">*</span><span class="dv">4</span>)</span></code></pre></div>
<p><img src="tsmodels_files/figure-html/prediction1-1.png" width="672" /></p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="tsets.html#cb41-1"></a>p_decomp &lt;-<span class="st"> </span><span class="kw">tsdecompose</span>(p)</span>
<span id="cb41-2"><a href="tsets.html#cb41-2"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>))</span>
<span id="cb41-3"><a href="tsets.html#cb41-3"></a><span class="kw">plot</span>(p_decomp<span class="op">$</span>Level, <span class="dt">main =</span> <span class="st">&quot;Level[State] Predicted Distribution&quot;</span>)</span>
<span id="cb41-4"><a href="tsets.html#cb41-4"></a><span class="kw">plot</span>(p_decomp<span class="op">$</span>Slope, <span class="dt">main =</span> <span class="st">&quot;Slope[State] Predicted Distribution&quot;</span>)</span>
<span id="cb41-5"><a href="tsets.html#cb41-5"></a><span class="kw">plot</span>(p_decomp<span class="op">$</span>Seasonal, <span class="dt">main =</span> <span class="st">&quot;Seasonal[State] Predicted Distribution&quot;</span>)</span>
<span id="cb41-6"><a href="tsets.html#cb41-6"></a><span class="kw">plot</span>(p_decomp<span class="op">$</span>Error, <span class="dt">main =</span> <span class="st">&quot;Simulated Error Distribution&quot;</span>)</span></code></pre></div>
<p><img src="tsmodels_files/figure-html/prediction_decomp-1.png" width="768" /></p>
<p>Since we left 52 points for out-of-sample testing, we are able to evaluate the prediction using the <code>tsmetrics</code> method on a predicted object. This method also takes the original series as an input in order to calculate MASE in the presence of seasonality. The alpha parameter is the coverage rate for calculation of the Mean Interval Score of <span class="citation">Gneiting and Raftery (<a href="#ref-gneiting2007" role="doc-biblioref">2007</a>)</span>.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="tsets.html#cb42-1"></a><span class="kw">tsmetrics</span>(p, <span class="kw">tail</span>(gas, <span class="dv">52</span>), <span class="dt">original_series =</span> spec<span class="op">$</span>target<span class="op">$</span>y_orig, <span class="dt">alpha =</span> <span class="fl">0.05</span>)</span></code></pre></div>
<pre><code>##    h       MAPE      MASE        MSLRE        BIAS    MIS
## 1 52 0.01445789 0.4013524 0.0003933292 0.003362753 1088.3</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="tsets.html#cb44-1"></a>tsd_predict &lt;-<span class="st"> </span><span class="kw">tsdecompose</span>(p)</span>
<span id="cb44-2"><a href="tsets.html#cb44-2"></a><span class="kw">par</span>(<span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>))</span>
<span id="cb44-3"><a href="tsets.html#cb44-3"></a><span class="kw">plot</span>(tsd_predict<span class="op">$</span>forecast, <span class="dt">main =</span> <span class="st">&quot;Prediction&quot;</span>)</span>
<span id="cb44-4"><a href="tsets.html#cb44-4"></a><span class="kw">plot</span>(tsd_predict<span class="op">$</span>Level, <span class="dt">main =</span> <span class="st">&quot;Level[State]&quot;</span>)</span>
<span id="cb44-5"><a href="tsets.html#cb44-5"></a><span class="kw">plot</span>(tsd_predict<span class="op">$</span>Slope, <span class="dt">main =</span> <span class="st">&quot;Slope[State]&quot;</span>)</span>
<span id="cb44-6"><a href="tsets.html#cb44-6"></a><span class="kw">plot</span>(tsd_predict<span class="op">$</span>Seasonal, <span class="dt">main =</span> <span class="st">&quot;Seasonal[State]&quot;</span>)</span></code></pre></div>
<p><img src="tsmodels_files/figure-html/prediction2-1.png" width="768" /></p>
</div>
<div id="tsets:demonstration:filtering" class="section level3">
<h3><span class="header-section-number">4.6.4</span> Filtering</h3>
<p>Online filtering is when new data arrives and instead of re-estimating the model, we instead just filter the new data based on an existing model. In the <strong>tsets</strong> package the <code>tsfilter</code> method updates an object of class <code>tsmodel.estimate</code> with new data as the example below illustrates. Because the class of the model is retained and only updated (both data and states) with new information, it is also possible to apply any method to that which admits that object (e.g. <code>predict</code>).</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="tsets.html#cb45-1"></a>mod_filter &lt;-<span class="st"> </span><span class="kw">tsfilter</span>(mod, <span class="dt">y =</span> gas[(<span class="kw">NROW</span>(gas) <span class="op">-</span><span class="st"> </span><span class="dv">52</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>)])</span>
<span id="cb45-2"><a href="tsets.html#cb45-2"></a><span class="kw">tail</span>(<span class="kw">fitted</span>(mod),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##              fitted
## 2004-05-07 9259.272</code></pre>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="tsets.html#cb47-1"></a><span class="kw">tail</span>(<span class="kw">fitted</span>(mod_filter),<span class="dv">2</span>)</span></code></pre></div>
<pre><code>##              fitted
## 2004-05-07 9259.272
## 2004-05-14 9146.997</code></pre>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="tsets.html#cb49-1"></a>mod_filter &lt;-<span class="st"> </span><span class="kw">tsfilter</span>(mod_filter, <span class="dt">y =</span> gas[(<span class="kw">NROW</span>(gas) <span class="op">-</span><span class="st"> </span><span class="dv">52</span> <span class="op">+</span><span class="st"> </span><span class="dv">2</span>)])</span>
<span id="cb49-2"><a href="tsets.html#cb49-2"></a><span class="kw">tail</span>(<span class="kw">fitted</span>(mod),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##              fitted
## 2004-05-07 9259.272</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="tsets.html#cb51-1"></a><span class="kw">tail</span>(<span class="kw">fitted</span>(mod_filter),<span class="dv">3</span>)</span></code></pre></div>
<pre><code>##              fitted
## 2004-05-07 9259.272
## 2004-05-14 9146.997
## 2004-05-21 9125.058</code></pre>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="tsets.html#cb53-1"></a><span class="kw">head</span>(<span class="kw">predict</span>(mod, <span class="dt">h =</span> <span class="dv">12</span>)<span class="op">$</span>mean)</span></code></pre></div>
<pre><code>## 2004-05-14 2004-05-21 2004-05-28 2004-06-04 2004-06-11 2004-06-18 
##   9162.706   9139.950   9118.101   9322.523   9406.679   9467.352</code></pre>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="tsets.html#cb55-1"></a><span class="kw">head</span>(<span class="kw">predict</span>(mod_filter, <span class="dt">h =</span> <span class="dv">12</span>)<span class="op">$</span>mean)</span></code></pre></div>
<pre><code>## 2004-05-28 2004-06-04 2004-06-11 2004-06-18 2004-06-25 2004-07-02 
##   9122.006   9316.075   9409.362   9436.874   9325.672   9452.225</code></pre>
</div>
<div id="tsets:demonstration:simulation" class="section level3">
<h3><span class="header-section-number">4.6.5</span> Simulation</h3>
<p>An estimated object can also be simulated from, with the parameters and initial states overridden by passing them as named values in the <code>pars</code> argument. The default is to initialize the states from the seed states used in the estimated object, with <code>h</code> equal to the length of the original series (default for <code>NULL</code> <code>h</code>).
Innovations for the simulation can either be parametric (normal for additive or truncated normal for multiplicative error models), based on the estimated residuals (<code>bootstrap</code> argument) or a user supplied set of uniform random numbers (which are then translated into normal or truncated normal using standard deviation equal to the model sigma and optionally scaled by <code>sigma_scale</code>).</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="tsets.html#cb57-1"></a>sim &lt;-<span class="st"> </span><span class="kw">simulate</span>(mod, <span class="dt">nsim =</span> <span class="dv">10</span>, <span class="dt">h =</span> <span class="dv">52</span><span class="op">*</span><span class="dv">2</span>)</span>
<span id="cb57-2"><a href="tsets.html#cb57-2"></a><span class="kw">plot</span>(sim)</span></code></pre></div>
<p><img src="tsmodels_files/figure-html/simulation-1.png" width="768" /></p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="tsets.html#cb58-1"></a><span class="kw">par</span>(<span class="dt">mar =</span> <span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>,<span class="dv">3</span>), <span class="dt">mfrow =</span> <span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">1</span>))</span>
<span id="cb58-2"><a href="tsets.html#cb58-2"></a><span class="kw">matplot</span>(<span class="kw">as.Date</span>(<span class="kw">colnames</span>(sim<span class="op">$</span>Simulated)), <span class="kw">t</span>(sim<span class="op">$</span>Simulated[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, ]), <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>,</span>
<span id="cb58-3"><a href="tsets.html#cb58-3"></a>        <span class="dt">ylab =</span> <span class="st">&quot;&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Simulated Paths&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb58-4"><a href="tsets.html#cb58-4"></a><span class="kw">grid</span>()</span>
<span id="cb58-5"><a href="tsets.html#cb58-5"></a><span class="kw">matplot</span>(<span class="kw">as.Date</span>(<span class="kw">colnames</span>(sim<span class="op">$</span>Simulated)), <span class="kw">t</span>(sim<span class="op">$</span>Level[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, ]), <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, </span>
<span id="cb58-6"><a href="tsets.html#cb58-6"></a>        <span class="dt">ylab =</span> <span class="st">&quot;&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Simulated Level&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb58-7"><a href="tsets.html#cb58-7"></a><span class="kw">grid</span>()</span>
<span id="cb58-8"><a href="tsets.html#cb58-8"></a><span class="kw">matplot</span>(<span class="kw">as.Date</span>(<span class="kw">colnames</span>(sim<span class="op">$</span>Simulated)), <span class="kw">t</span>(sim<span class="op">$</span>Slope[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, ]), <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, </span>
<span id="cb58-9"><a href="tsets.html#cb58-9"></a>        <span class="dt">ylab =</span> <span class="st">&quot;&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Simulated Slope&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb58-10"><a href="tsets.html#cb58-10"></a><span class="kw">grid</span>()</span>
<span id="cb58-11"><a href="tsets.html#cb58-11"></a><span class="co"># not much on the seasonal since gamma coefficient is zero</span></span>
<span id="cb58-12"><a href="tsets.html#cb58-12"></a><span class="kw">matplot</span>(<span class="kw">as.Date</span>(<span class="kw">colnames</span>(sim<span class="op">$</span>Simulated)), <span class="kw">t</span>(sim<span class="op">$</span>Seasonal[<span class="dv">1</span><span class="op">:</span><span class="dv">10</span>, ]), <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, </span>
<span id="cb58-13"><a href="tsets.html#cb58-13"></a>        <span class="dt">ylab =</span> <span class="st">&quot;&quot;</span>, <span class="dt">main =</span> <span class="st">&quot;Simulated Seasonal&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;&quot;</span>)</span>
<span id="cb58-14"><a href="tsets.html#cb58-14"></a><span class="kw">grid</span>()</span></code></pre></div>
<p><img src="tsmodels_files/figure-html/simulation-2.png" width="768" /></p>
</div>
<div id="tsets:demonstration:profiling" class="section level3">
<h3><span class="header-section-number">4.6.6</span> Profiling</h3>
<p>The <code>tsprofile</code> function profiles an estimated model by simulating and then estimating multiple paths from the assumed DGP while leaving <code>h</code> values out for prediction evaluation. Each simulated path is equal to the size of the original dataset plus <code>h</code> additional values, and initialized with the initial state vector from the model. The resulting output contains the distribution of the MAPE, percent bias (BIAS) and mean squared log relative error (MSLRE) per horizon <code>h</code>. Since these matrices are of class <code>tsmodel.distribution</code>, they can be readily plotted with the special purpose <code>plot</code> function for this class from the <strong>tsmethods</strong> package. Additionally, a data.table matrix is also return with the distribution of the coefficients from each path estimation.</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="tsets.html#cb59-1"></a><span class="co"># profiling</span></span>
<span id="cb59-2"><a href="tsets.html#cb59-2"></a>prof &lt;-<span class="st"> </span><span class="kw">tsprofile</span>(mod, <span class="dt">h =</span> <span class="dv">52</span>, <span class="dt">nsim =</span> <span class="dv">1000</span>, <span class="dt">cores =</span> <span class="dv">4</span>, <span class="dt">trace =</span> <span class="dv">0</span>)</span>
<span id="cb59-3"><a href="tsets.html#cb59-3"></a><span class="kw">plot</span>(prof, <span class="dt">type =</span> <span class="st">&quot;metrics&quot;</span>)</span></code></pre></div>
<p><img src="tsmodels_files/figure-html/profile-1.png" width="768" /></p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="tsets.html#cb60-1"></a><span class="kw">plot</span>(prof, <span class="dt">type =</span> <span class="st">&quot;coef&quot;</span>)</span></code></pre></div>
<p><img src="tsmodels_files/figure-html/profile-2.png" width="768" /></p>
</div>
<div id="tsets:demonstration:backtesting" class="section level3">
<h3><span class="header-section-number">4.6.7</span> Backtesting</h3>
<p>The <code>tsbacktest</code> method generates an expanding window, walk forward backtest, returning a list with the estimation/horizon predictions against actuals, as well as a table of average performance metrics by horizon.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="tsets.html#cb61-1"></a>b &lt;-<span class="st"> </span><span class="kw">tsbacktest</span>(spec, <span class="dt">h =</span> <span class="dv">52</span>, <span class="dt">alpha =</span> <span class="kw">c</span>(<span class="fl">0.02</span>, <span class="fl">0.1</span>), <span class="dt">trace =</span> <span class="dv">0</span>, <span class="dt">cores =</span> <span class="dv">4</span>)</span>
<span id="cb61-2"><a href="tsets.html#cb61-2"></a><span class="kw">head</span>(b<span class="op">$</span>metrics)</span></code></pre></div>
<pre><code>##    horizon variable       MAPE       MSLRE          BIAS   n MIS[0.02] MIS[0.1]
## 1:       1        y 0.02719118 0.001169433 -0.0004603201 347  1679.139 1188.918
## 2:       2        y 0.02693041 0.001155618 -0.0004865995 346  1708.493 1188.310
## 3:       3        y 0.02705806 0.001158089 -0.0003868899 345  1686.740 1175.872
## 4:       4        y 0.02708764 0.001164290 -0.0004667140 344  1709.906 1183.159
## 5:       5        y 0.02708754 0.001163591 -0.0004585236 343  1734.368 1186.050
## 6:       6        y 0.02687278 0.001146714 -0.0006670401 342  1695.671 1183.411</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="tsets.html#cb63-1"></a><span class="kw">plot</span>(b<span class="op">$</span>metrics<span class="op">$</span>horizon, b<span class="op">$</span>metrics<span class="op">$</span>MAPE<span class="op">*</span><span class="dv">100</span>, <span class="dt">main =</span> <span class="st">&quot;Horizon MAPE&quot;</span>, <span class="dt">type =</span> <span class="st">&quot;l&quot;</span>, </span>
<span id="cb63-2"><a href="tsets.html#cb63-2"></a>     <span class="dt">ylab =</span> <span class="st">&quot;MAPE[%]&quot;</span>, <span class="dt">xlab =</span> <span class="st">&quot;horizon&quot;</span>)</span>
<span id="cb63-3"><a href="tsets.html#cb63-3"></a><span class="kw">grid</span>()</span></code></pre></div>
<p><img src="tsmodels_files/figure-html/backtest-1.png" width="672" /></p>
</div>
<div id="tsets:demonstration:benchmarking" class="section level3">
<h3><span class="header-section-number">4.6.8</span> Benchmarking</h3>
<p>The <code>tsbenchmark</code> method is used to benchmark a model for timing and accuracy and can be used as a unit testing function.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="tsets.html#cb64-1"></a>bench &lt;-<span class="st"> </span><span class="kw">rbind</span>(<span class="kw">tsbenchmark</span>(spec, <span class="dt">solver =</span> <span class="st">&quot;optim&quot;</span>), </span>
<span id="cb64-2"><a href="tsets.html#cb64-2"></a>      <span class="kw">tsbenchmark</span>(spec, <span class="dt">solver =</span> <span class="st">&quot;nlminb&quot;</span>),</span>
<span id="cb64-3"><a href="tsets.html#cb64-3"></a>      <span class="kw">tsbenchmark</span>(spec, <span class="dt">solver =</span> <span class="st">&quot;solnp&quot;</span>))</span>
<span id="cb64-4"><a href="tsets.html#cb64-4"></a>bench</span></code></pre></div>
<pre><code>##                  start                 end            spec            estimate
## 1: 2020-11-25 14:11:28 2020-11-25 14:11:28 &lt;tsets.spec[5]&gt; &lt;tsets.estimate[3]&gt;
## 2: 2020-11-25 14:11:28 2020-11-25 14:11:28 &lt;tsets.spec[5]&gt; &lt;tsets.estimate[3]&gt;
## 3: 2020-11-25 14:11:28 2020-11-25 14:11:29 &lt;tsets.spec[5]&gt; &lt;tsets.estimate[3]&gt;
##    solver control    loglik
## 1:  optim       0 -6126.568
## 2: nlminb       0 -6125.014
## 3:  solnp       0 -6125.014</code></pre>

</div>
</div>
</div>
<h3>References</h3>
<div id="refs" class="references">
<div id="ref-brown1959">
<p>Brown, Robert Goodell. 1959. <em>Statistical Forecasting for Inventory Control</em>. McGraw/Hill.</p>
</div>
<div id="ref-brown1962">
<p>Brown, Robert Goodell. 1962. “Smoothing, Forecasting and Prediction of Discrete Time Series.”</p>
</div>
<div id="ref-casals1999">
<p>Casals, José, Sonia Sotoca, and Miguel Jerez. 1999. “A Fast and Stable Method to Compute the Likelihood of Time Invariant State-Space Models.” <em>Economics Letters</em> 65 (3): 329–37.</p>
</div>
<div id="ref-desilva2010">
<p>De Silva, Ashton, Rob J Hyndman, and Ralph Snyder. 2010. “The Vector Innovations Structural Time Series Framework: A Simple Approach to Multivariate Forecasting.” <em>Statistical Modelling</em> 10 (4): 353–74.</p>
</div>
<div id="ref-gardner1985">
<p>Gardner Jr, ES. 1985. “Exponential Smoothing: The State of the Art.” <em>Journal of Forecasting</em> 4 (1): 1–28.</p>
</div>
<div id="ref-gneiting2007">
<p>Gneiting, Tilmann, and Adrian E Raftery. 2007. “Strictly Proper Scoring Rules, Prediction, and Estimation.” <em>Journal of the American Statistical Association</em> 102 (477): 359–78.</p>
</div>
<div id="ref-guerrero1993time">
<p>Guerrero, Victor M. 1993. “Time-Series Analysis Supported by Power Transformations.” <em>Journal of Forecasting</em> 12 (1): 37–48.</p>
</div>
<div id="ref-harvey1990">
<p>Harvey, Andrew C. 1990. <em>Forecasting, Structural Time Series Models and the Kalman Filter</em>. Cambridge university press.</p>
</div>
<div id="ref-holt1957">
<p>Holt, Charles. 1957. “Forecasting Trends and Seasonals by Exponential Weighted Averages.” <em>ONR Memorandum</em> 52: 1957.</p>
</div>
<div id="ref-hyndman2008a">
<p>Hyndman, Rob J, Muhammad Akram, and Blyth C Archibald. 2008. “The Admissible Parameter Space for Exponential Smoothing Models.” <em>Annals of the Institute of Statistical Mathematics</em> 60 (2): 407–26.</p>
</div>
<div id="ref-hyndman2002">
<p>Hyndman, Rob J, Anne B Koehler, Ralph D Snyder, and Simone Grose. 2002. “A State Space Framework for Automatic Forecasting Using Exponential Smoothing Methods.” <em>International Journal of Forecasting</em> 18 (3): 439–54.</p>
</div>
<div id="ref-hyndman2008">
<p>Hyndman, Rob, Anne B Koehler, J Keith Ord, and Ralph D Snyder. 2008. <em>Forecasting with Exponential Smoothing: The State Space Approach</em>. Springer Science &amp; Business Media.</p>
</div>
<div id="ref-koehler2001">
<p>Koehler, Anne B, Ralph D Snyder, and J Keith Ord. 2001. “Forecasting Models and Prediction Intervals for the Multiplicative Holt-Winters Method.” <em>International Journal of Forecasting</em> 17 (2): 269–86.</p>
</div>
<div id="ref-mckenzie1986">
<p>McKenzie, Ed. 1986. “Error Analysis for Winters’ Additive Seasonal Forecasting System.” <em>International Journal of Forecasting</em> 2 (3): 373–82.</p>
</div>
<div id="ref-ord1997">
<p>Ord, John Keith, Anne B Koehler, and Ralph D Snyder. 1997. “Estimation and Prediction for a Class of Dynamic Nonlinear Statistical Models.” <em>Journal of the American Statistical Association</em> 92 (440): 1621–9.</p>
</div>
<div id="ref-pegels">
<p>Pegels, C. Carl. 1969. “Exponential Forecasting: Some New Variations.” <em>Management Science</em> 15 (5): 311–15.</p>
</div>
<div id="ref-roberts1982">
<p>Roberts, SA. 1982. “A General Class of Holt-Winters Type Forecasting Models.” <em>Management Science</em> 28 (7): 808–20.</p>
</div>
<div id="ref-scott2015">
<p>Scott, Steven L, and Hal R Varian. 2015. “Bayesian Variable Selection for Nowcasting Economic Time Series.” <em>Economic Analysis of the Digital Economy</em>, 119–35.</p>
</div>
<div id="ref-taylor2003">
<p>Taylor, James W. 2003. “Exponential Smoothing with a Damped Multiplicative Trend.” <em>International Journal of Forecasting</em> 19 (4): 715–25.</p>
</div>
<div id="ref-west2006">
<p>West, Mike, and Jeff Harrison. 2006. <em>Bayesian Forecasting and Dynamic Models</em>. Springer Science &amp; Business Media.</p>
</div>
<div id="ref-winters1960">
<p>Winters, Peter R. 1960. “Forecasting Sales by Exponentially Weighted Moving Averages.” <em>Management Science</em> 6 (3): 324–42.</p>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="5">
<li id="fn5"><p>Also called Single Source of Error (SSOE) models.<a href="tsets.html#fnref5" class="footnote-back">↩︎</a></p></li>
<li id="fn6"><p>See <span class="citation">Hyndman et al. (<a href="#ref-hyndman2002" role="doc-biblioref">2002</a>)</span> chapter 11.<a href="tsets.html#fnref6" class="footnote-back">↩︎</a></p></li>
<li id="fn7"><p>The adjugate of a matrix <span class="math inline">\(\mathbf{A}\)</span> is the transpose of the cofactor matrix <span class="math inline">\(\mathbf{C}\)</span> of <span class="math inline">\(\mathbf{A}\)</span>: <span class="math inline">\(adj\left(\mathbf{A}\right)=\mathbf{C}^\mathbf{T}\)</span>.<a href="tsets.html#fnref7" class="footnote-back">↩︎</a></p></li>
<li id="fn8"><p>After the elimination of any common factors between the polynomials.<a href="tsets.html#fnref8" class="footnote-back">↩︎</a></p></li>
<li id="fn9"><p>In the terminology of the ETS models this is (A,Ad,N).<a href="tsets.html#fnref9" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="tsmethods.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="tsissm.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
